routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\PublisherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', [BookController::class, 'index']);

// Route::get('/category', [CategoryController::class, 'index']);
// Route::post('/category', [CategoryController::class, 'store']);

// Route::get('/author', [AuthorController::class, 'index']);

// Route::get('/publisher', [PublisherController::class, 'index']);
Route::resource('/', BookController::class);
Route::resource('book', BookController::class);
Route::resource('category', CategoryController::class);
Route::resource('author', AuthorController::class);
Route::resource('publisher', PublisherController::class);

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $guarded = [
        'id'
    ];


    public function category() 
    {
        return $this->belongsTo(Category::class);
    }
    

    public function author() 
    {
        return $this->belongsTo(Author::class);
    }


    public function publisher() 
    {
        return $this->belongsTo(Publisher::class);
    }
    
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;
use App\Models\Category;
use App\Models\Author;
use App\Models\Publisher;


class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Book $book)
    {
        return view('book.index', [
            'title' => 'book',
            'books' => $book->all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        $author = Author::all();
        $publisher = Publisher::all();

        return view('book.create', [
            'title' => 'book',
            'categories' => $category,
            'authors' => $author,
            'publishers' => $publisher
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'synopsis' => 'required',
            'author_id' => 'required',
            'category_id' => 'required',
            'publisher_id' => 'required',
            'year' => 'required'
        ]);

        Book::create($request->all());

        return redirect()->route('book.index')
                        ->with('success','Data buku berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {       
        $book = Book::find($id);

        $author_selected = $book->author_id;

        return view('book.edit', [
            'title' => 'book',
            'book' => Book::find($id),
            'authors' => Author::all(),
            'categories' => Category::all(),
            'publishers' => Publisher::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
        ]);
    
        $book = Book::find($id);
        $book->update($request->all());
    
        return redirect()->route('book.index')
                        ->with('success','Data buku berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);
        $book->delete();

        return redirect()->route('book.index')
                        ->with('success','Data buku berhasil dihapus');
    }
}

resources/views/book/create.blade.php
@extends('layouts.common')

@section('content')


<div class="row mb-5">
    <div class="col-12">   
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Periksa lagi data yang diinput.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif 

        <form id="form_book" action="{{ route('book.store') }}" method="POST">
            @csrf

            <div class="modal-header bg-light">
                <h5 class="modal-title" id="modal_title">Tambah Buku</h5>
                <a href="{{ route('book.index') }}">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </a>
            </div>

            <div class="modal-body">                
                <input type="hidden" class="form-control" name="action" id="book_action" value="add">
                <input type="hidden" class="form-control" name="id" id="book_id" value="">

                <div class="mb-3">
                    <label for="book_title" class="form-label">Judul</label>
                    <input type="text" class="form-control" name="title" id="book_title" value="">
                </div>

                <div class="mb-3">
                    <label for="book_synopsis" class="form-label">Sinopsis</label>
                    <input type="text" class="form-control" name="synopsis" id="book_synopsis" value="">
                </div>

                <div class="mb-3">
                    <label for="book_author" class="form-label">Penulis</label>
                    <select class="form-select" name="author_id" id="book_author" value="">
                        <option value="0">-</option>
                        @foreach ($authors as $index=>$author)
                            <option value="{{ $author->id }}">{{ $author->name }}</option>
                        @endforeach                       
                    </select>
                </div>

                <div class="mb-3">
                    <label for="book_category" class="form-label">Kategori</label>
                    <select class="form-select" name="category_id" id="book_category" value="">
                        <option value="0">-</option>
                        @foreach ($categories as $index=>$category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="mb-3">
                    <label for="book_publisher" class="form-label">Penerbit</label>
                    <select class="form-select" name="publisher_id" id="book_publisher" value="">
                        <option value="0">-</option>
                        @foreach ($publishers as $index=>$publisher)
                            <option value="{{ $publisher->id }}">{{ $publisher->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="mb-3">
                    <label for="book_year" class="form-label">Tahun</label>
                    <input type="number" class="form-control" name="year" id="book_release_year" value="">
                </div>
            </div>
            
            <div class="modal-footer d-flex justify-content-between">           
                <a href="{{ route('book.index') }}">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                </a>     
                <button type="submit" name="submit" class="btn btn-primary">Submit</button>
            </div>

        </form> 
        
    </div>
</div>


@endsection

resources/views/book/edit.blade.php
@extends('layouts.common')

@section('content')


<div class="row mb-5">
    <div class="col-12">   
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Periksa lagi data yang diinput.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif 

        <form id="form_book" action="{{ route('book.store') }}" method="POST">
            @csrf

            <div class="modal-header bg-light">
                <h5 class="modal-title" id="modal_title">Edit Buku</h5>
                <a href="{{ route('book.index') }}">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </a>
            </div>

            <div class="modal-body">                
                <input type="hidden" class="form-control" name="action" id="book_action" value="add">
                <input type="hidden" class="form-control" name="id" id="book_id" value="{{ $book->id }}">

                <div class="mb-3">
                    <label for="book_title" class="form-label">Judul</label>
                    <input type="text" class="form-control" name="title" id="book_title" value="{{ $book->title }}">
                </div>

                <div class="mb-3">
                    <label for="book_synopsis" class="form-label">Sinopsis</label>
                    <input type="text" class="form-control" name="synopsis" id="book_synopsis" value="{{ $book->synopsis }}">
                </div>

                <div class="mb-3">
                    <label for="book_author" class="form-label">Penulis</label>                    
                    <select class="form-select" name="author_id" id="book_author" value="">
                        <option value="0">-</option>
                        @foreach ($authors as $index=>$author)
                            <option value="{{ $author->id }}" 
                            @if ($book->author->name == $author->name) 
                            {{'selected="selected"'}}
                            @endif 
                            >
                            {{ $author->name }}</option>
                        @endforeach                       
                    </select>
                </div>

                <div class="mb-3">
                    <label for="book_category" class="form-label">Kategori</label>
                    <select class="form-select" name="category_id" id="book_category" value="">
                        <option value="0">-</option>
                        @foreach ($categories as $index=>$category)
                            <option value="{{ $category->id }}"
                            @if ($book->category->name == $category->name)
                            {{'selected="selected"'}}
                            @endif
                            >
                            {{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="mb-3">
                    <label for="book_publisher" class="form-label">Penerbit</label>
                    <select class="form-select" name="publisher_id" id="book_publisher" value="">
                        <option value="0">-</option>
                        @foreach ($publishers as $index=>$publisher)
                            <option value="{{ $publisher->id }}"
                            @if ($book->publisher->name == $publisher->name)
                            {{'selected="selected"'}}
                            @endif
                            >{{ $publisher->name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="mb-3">
                    <label for="book_year" class="form-label">Tahun</label>
                    <input type="number" class="form-control" name="year" id="year" value="{{$book->year}}">
                </div>
            </div>
            
            <div class="modal-footer d-flex justify-content-between">           
                <a href="{{ route('book.index') }}">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                </a>     
                <button type="submit" name="submit" class="btn btn-primary">Submit</button>
            </div>

        </form> 
        
    </div>
</div>


@endsection

resources/views/book/index.blade.php
@extends('layouts.common')


@section('content')


<div class="d-flex justify-content-between">
    <h5 class="display-6">Daftar Buku</h5>
    <a href="{{ route('book.create') }}">
        <button type="button" class="btn btn-sm btn-outline-success p-3 btn-add-cat" 
            data-bs-action="add">
            <svg id="i-plus" xmlns="http://www.w3.org/2000/svg" 
                viewBox="0 0 32 32" width="24" height="24" fill="none" 
                stroke="currentcolor" stroke-linecap="round" 
                stroke-linejoin="round" stroke-width="2">
                <path d="M16 2 L16 30 M2 16 L30 16" />
            </svg>
            <span class="px-3 align-bottom">Tambah</span> 
        </button>            
    </a>

</div>
<hr/>

<div class="mb-5"></div>

<table class="table table-hover" id="table_book">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Judul</th>
            <th scope="col">Sinopsis</th>
            <th scope="col">Penulis</th>
            <th scope="col">Kategori</th>
            <th scope="col">Penerbit</th>
            <th scope="col">Tahun</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>

        @foreach ($books as $index=>$book)
            <tr>
                <th scope="row">{{ $index += 1 }}</th>
                <td>{{ $book->title }}</td>
                <td scope="col">{{ $book->synopsis }}</td>
                <td scope="col">{{ $book->author->name }}</td>
                <td scope="col">{{ $book->category->name }}</td>
                <td scope="col">{{ $book->publisher->name }}</td>
                <td scope="col">{{ $book->year }}</td>
                <td>
                    <form action="{{ route('book.destroy', $book->id) }}" method="POST">
                        <a type="button" class="btn btn-sm btn-outline-warning mx-2" href="{{ route('book.edit', $book->id) }}">
                            <svg id="i-edit" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                <path d="M30 7 L25 2 5 22 3 29 10 27 Z M21 6 L26 11 Z M5 22 L10 27 Z" />
                            </svg>
                        </a> 
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-sm btn-outline-danger mx-auto">
                            <svg id="i-trash" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                <path d="M28 6 L6 6 8 30 24 30 26 6 4 6 M16 12 L16 24 M21 12 L20 24 M11 12 L12 24 M12 6 L13 2 19 2 20 6" />
                            </svg>       
                        </button>   
                    </form>
                </td>
            </tr>
        @endforeach
            
    </tbody>
</table>


<script>

$(document).ready(function() {
    $('#table_book').DataTable();
})

</script>

@endsection