routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\PublisherController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', [BookController::class, 'index']);

// Route::get('/category', [CategoryController::class, 'index']);
// Route::post('/category', [CategoryController::class, 'store']);

// Route::get('/author', [AuthorController::class, 'index']);

// Route::get('/publisher', [PublisherController::class, 'index']);
Route::resource('/', BookController::class);
Route::resource('book', BookController::class);
Route::resource('category', CategoryController::class);
Route::resource('author', AuthorController::class);
Route::resource('publisher', PublisherController::class);

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    use HasFactory;

    protected $guarded = [
        'id'
    ];
    
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Author;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Author $author) 
    {
        return view('author/index', [
            'title' => 'author',
            'authors' => $author->all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('author.create', [
            'title' => 'author'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required'
        ]);

        Author::create($request->all());

        return redirect()->route('author.index')
                        ->with('success','Data penulis berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('author.edit', [
            'title' => 'author',
            'author' => Author::find($id),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
        ]);
    
        $author = Author::find($id);
        $author->update($request->all());
    
        return redirect()->route('author.index')
                        ->with('success','Data penulis berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $author = Author::find($id);
        $author->delete();

        return redirect()->route('author.index')
                        ->with('success','Data penulis berhasil dihapus');
    }
}

resources/views/author/create.blade.php
@extends('layouts.common')

@section('content')

<div class="row mb-5">
    <div class="col-12">   
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Periksa lagi data yang diinput.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif 
        <form id="form_author" action="{{ route('author.store') }}" method="POST">
            @csrf

            <div class="modal-header bg-light">
                <h5 class="modal-title" id="modal_title">Tambah Kategori</h5>
                <a href="{{ route('author.index') }}">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </a>
            </div>

            <div class="modal-body">                
                <input type="hidden" class="form-control" name="action" id="author_action" value="add">
                <input type="hidden" class="form-control" name="id" id="author_id" value="">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Nama</label>
                    <input type="text" class="form-control" name="name" id="author_name" value="">
                </div>                    
            </div>

            <div class="modal-footer d-flex justify-content-between">            
                <a href="{{ route('author.index') }}">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                </a>
                <button type="submit" name="submit" class="btn btn-primary">Submit</button>            
            </div>

        </form> 
    </div>
</div>


@endsection

resources/views/author/edit.blade.php
@extends('layouts.common')

@section('content')

<div class="row mb-5">
    <div class="col-12">   
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Periksa lagi data yang diinput.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif 
        <form id="form_author" action="{{ route('author.update', $author->id) }}" method="POST">
            @csrf
            @method('PUT')

            <div class="modal-header bg-light">
                <h5 class="modal-title" id="modal_title">Edit Penulis</h5>
                <a href="{{ route('author.index') }}">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </a>
            </div>

            <div class="modal-body">                
                <input type="hidden" class="form-control" name="action" id="author_action" value="add">
                <input type="hidden" class="form-control" name="id" id="author_id" value="">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Nama</label>
                    <input type="text" class="form-control" name="name" id="author_name" value="{{ $author->name }}">
                </div>                    
            </div>

            <div class="modal-footer d-flex justify-content-between"> 
                <a href="{{ route('author.index') }}">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                </a>
                <button type="submit" name="submit" class="btn btn-primary">Submit</button>                
            </div>

        </form> 
    </div>
</div>


@endsection

resources/views/author/index.blade.php
@extends('layouts.common')

@section('content')

<div class="d-flex justify-content-between">
    <h5 class="display-6">Daftar Penulis</h5>
    <a href="{{ route('author.create') }}">
        <button type="button" class="btn btn-sm btn-outline-success p-3 btn-add-cat" 
        data-bs-action="add">
            <svg id="i-plus" xmlns="http://www.w3.org/2000/svg" 
                viewBox="0 0 32 32" width="24" height="24" fill="none" 
                stroke="currentcolor" stroke-linecap="round" 
                stroke-linejoin="round" stroke-width="2">
                <path d="M16 2 L16 30 M2 16 L30 16" />
            </svg>
        
            <span class="px-3 align-bottom">Tambah</span> 
        </button>            
    </a>

</div>
<hr/>

<div class="mb-5"></div>
@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif

<table class="table table-hover" id="table_author">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nama</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($authors as $index=>$author)
            <tr>
                <th scope="row">{{ $index += 1 }}</th>
                <td>{{ $author->name }}</td>
                <td>
                    <form action="{{ route('author.destroy', $author->id) }}" method="POST">
                        <a class="btn btn-sm btn-outline-warning mx-2" href="{{ route('author.edit', $author->id) }}">
                            <svg id="i-edit" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                <path d="M30 7 L25 2 5 22 3 29 10 27 Z M21 6 L26 11 Z M5 22 L10 27 Z" />
                            </svg>
                        </a> 
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-sm btn-outline-danger mx-auto" >
                            <svg id="i-trash" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                <path d="M28 6 L6 6 8 30 24 30 26 6 4 6 M16 12 L16 24 M21 12 L20 24 M11 12 L12 24 M12 6 L13 2 19 2 20 6" />
                            </svg>       
                        </button>   
                    </form>
                </td>
            </tr>
        @endforeach
            
    </tbody>
</table>


<script>

$(document).ready(function() {

    $('#table_author').DataTable();

})

</script>

@endsection